trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main

variables:
  # Only define static/computed values here.
  # Secrets (AZURE_SP_PASSWORD, AZURE_STATIC_WEBAPP_API_TOKEN) must be set in Azure DevOps Variable Group / Pipeline UI.
  AZURE_RESOURCE_GROUP: "Rental-Management"
  AZURE_STATIC_WEBAPP_NAME: "rental-management-frontend"
  AZURE_SUBSCRIPTION_ID: "bf912271-f73c-4e2a-b886-17c8fcdf8894"
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '18.x'
  SELF_HOSTED_POOL: 'self-hosted-pool'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildBackend
        displayName: Build & Test Backend
        pool:
          name: $(SELF_HOSTED_POOL)
          demands:
            - agent.os -equals Windows_NT
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET SDK'
            inputs:
              packageType: 'sdk'
              version: $(DOTNET_VERSION)

          - task: CmdLine@2
            displayName: 'dotnet restore/build/test'
            inputs:
              script: |
                cd backend
                dotnet restore
                dotnet build --configuration Release --no-restore
                dotnet test --no-build --verbosity normal || echo "Tests failed (continuing pipeline)."
                cd ..

          - task: CmdLine@2
            displayName: 'dotnet publish'
            inputs:
              script: |
                cd backend
                dotnet publish -c Release -o "$(Build.ArtifactStagingDirectory)/backend_publish"
                cd ..

          - publish: $(Build.ArtifactStagingDirectory)/backend_publish
            artifact: backend_artifact

      - job: BuildFrontend
        displayName: Build Frontend
        pool:
          name: $(SELF_HOSTED_POOL)
          demands:
            - agent.os -equals Windows_NT
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: 'Use Node'

          - task: CmdLine@2
            displayName: 'npm install & build (Vite)'
            inputs:
              script: |
                cd frontend
                npm install
                npm run build
                cd ..

          - publish: frontend/dist
            artifact: frontend_artifact

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    jobs:
      - deployment: DeployFrontend
        displayName: Deploy Frontend to Azure Static Web Apps
        environment: 'static-web-app'
        pool:
          name: $(SELF_HOSTED_POOL)
          demands:
            - agent.os -equals Windows_NT
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: frontend_artifact

                - task: CmdLine@2
                  displayName: 'Deploy frontend to Azure Static Web App (via az cli)'
                  inputs:
                    script: |
                      az --version || (echo "Azure CLI missing on agent" && exit 1)
                      az login --service-principal -u "$(AZURE_SP_APPID)" -p "$(AZURE_SP_PASSWORD)" --tenant "$(AZURE_SP_TENANT)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      if [ -z "$(AZURE_STATIC_WEBAPP_API_TOKEN)" ]; then
                        echo "AZURE_STATIC_WEBAPP_API_TOKEN not set."
                        exit 1
                      fi
                      DIST_PATH="$(Pipeline.Workspace)/frontend_artifact/dist"
                      if [ ! -d "$DIST_PATH" ]; then
                        echo "Frontend build output not found at $DIST_PATH"
                        exit 1
                      fi
                      az staticwebapp upload --name "$(AZURE_STATIC_WEBAPP_NAME)" --resource-group "$(AZURE_RESOURCE_GROUP)" --source "$DIST_PATH" --subscription "$(AZURE_SUBSCRIPTION_ID)"

      - deployment: DeployBackend
        displayName: Deploy Backend to Azure App Service
        environment: 'app-service'
        pool:
          name: $(SELF_HOSTED_POOL)
          demands:
            - agent.os -equals Windows_NT
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: backend_artifact

                - task: CmdLine@2
                  displayName: 'Deploy backend via az cli (zip deploy)'
                  inputs:
                    script: |
                      az --version || (echo "Azure CLI missing on agent" && exit 1)
                      az login --service-principal -u "$(AZURE_SP_APPID)" -p "$(AZURE_SP_PASSWORD)" --tenant "$(AZURE_SP_TENANT)"
                      az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
                      cd "$(Pipeline.Workspace)/backend_artifact"
                      ZIP_PATH="$TEMP/backend_publish.zip"
                      if [ -f "$ZIP_PATH" ]; then rm -f "$ZIP_PATH"; fi
                      powershell -Command "Compress-Archive -Path * -DestinationPath '$ZIP_PATH' -Force"
                      cd ..
                      az webapp deploy --resource-group "$(AZURE_RESOURCE_GROUP)" --name "$(AZURE_WEBAPP_NAME)" --src-path "$ZIP_PATH" --type zip